def build(bld):
    import lumberyard_sdks

    bld.DefineGem(
        includes = [bld.Path('Code/CryEngine/CryAction'),
                    bld.Path('Code/CryEngine/CryAction/FlowSystem/Nodes'),
                    bld.Path('Code/CryEngine/LmbrAWS')],
        win_use = ['AWS-CPP-SDK-CORE'],
        win_features = ['AWSNativeSDK'],
        uselib = ['AWS_CPP_SDK_CORE']
    )
