on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Switch to SDKBuildScripts directory
      run: cd SDKBuildScripts
    - name: Generate Go SDK
      run: .\go_build.bat
    - name: Switch to output directory
      run: cd ..\..\sdks\GoSDK\sdk
    - name: Init Go Modules
      run: go mod init
    - name: Test
      run: go test ./...